version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_NAME} # Название базы данных в PostgreSQL
      POSTGRES_USER: ${PG_USER} # Имя пользователя в базе данных PostgreSQL
      POSTGRES_PASSWORD: ${PG_PASS} # Пароль к базе данных PostgreSQL
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_shop

  aiogram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: ${TOKEN} # Токен полученный в ТГ у @BotFather
      ADMIN_ID: ${ADMIN_ID} # ID пользователя, полученное у @getmyid_bot
      PG_USER: ${PG_USER} # Имя пользователя в базе данных PostgreSQL
      PG_PASS: ${PG_PASS} # Пароль к базе данных PostgreSQL
      PG_HOST: db # Это хост базы данных к сервису db, его оставить без изменений!!!
      PG_NAME: ${PG_NAME} # Название базы данных в PostgreSQL
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY} # Секретный ключ yookassa
      YOOKASSA_ACCIUNT_ID: ${YOOKASSA_ACCIUNT_ID} # ID магазина в системе
    depends_on:
      - db
    networks:
      - bot_shop

volumes:
  postgres_data:

networks:
  bot_shop: